import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { buildCssVars } from '../hooks/useTokens';

function buildTokensMd(tokens, name) {
  return `# ${name} — Design Tokens

Generated by Design System Studio — https://github.com/YOUR_USERNAME/design-system-studio

To theme a new project: update the values in the "CONFIGURE THESE" sections.
All component CSS stays the same — it inherits the new values automatically.

---

## 🎨 CONFIGURE THESE — Brand Colors

\`\`\`css
--color-brand:        ${tokens.brand};
--color-brand-light:  ${tokens.brandLight};
--color-brand-dark:   ${tokens.brandDark};

--color-neutral-50:   #F8F8F7;
--color-neutral-100:  #EDEDEB;
--color-neutral-200:  #D9D8D4;
--color-neutral-400:  #9B9A94;
--color-neutral-600:  #57564F;
--color-neutral-800:  #2A2924;
--color-neutral-900:  ${tokens.neutral};

--color-success:      #1D9E75;
--color-warning:      #BA7517;
--color-danger:       #E24B4A;
--color-info:         #378ADD;

--color-surface-0:    #FFFFFF;
--color-surface-1:    #F8F8F7;
--color-surface-2:    #EDEDEB;
\`\`\`

---

## 🔤 CONFIGURE THESE — Typography

\`\`\`css
--font-display:  ${tokens.fontDisplay};
--font-body:     ${tokens.fontBody};
--font-mono:     'JetBrains Mono', monospace;

--text-xs:    0.75rem;
--text-sm:    0.875rem;
--text-base:  1rem;
--text-lg:    1.125rem;
--text-xl:    1.25rem;
--text-2xl:   1.5rem;
--text-3xl:   1.875rem;
--text-4xl:   2.25rem;
--text-5xl:   3rem;

--weight-regular: 400;
--weight-medium:  500;
--weight-bold:    700;

--leading-tight:  1.2;
--leading-normal: 1.6;
--leading-loose:  1.8;
\`\`\`

---

## 📐 CONFIGURE THESE — Spacing & Border Radius

\`\`\`css
--space-1:   4px;
--space-2:   8px;
--space-3:   12px;
--space-4:   16px;
--space-5:   20px;
--space-6:   24px;
--space-8:   32px;
--space-10:  40px;
--space-12:  48px;
--space-16:  64px;
--space-20:  80px;
--space-24:  96px;

--radius-sm:   ${tokens.radiusSm};
--radius-md:   ${tokens.radiusMd};
--radius-lg:   ${tokens.radiusLg};
--radius-pill: ${tokens.radiusPill};

--border-thin:   1px;
--border-medium: 1.5px;
--border-thick:  2px;
--border-style:  ${tokens.borderStyle};
\`\`\`

---

## 🌑 Shadows

\`\`\`css
${tokens.shadow === 'none' ? `--shadow-sm:  none;
--shadow-md:  none;
--shadow-lg:  none;
--shadow-xl:  none;` : tokens.shadow === 'sm' ? `--shadow-sm:  0 1px 2px 0 rgba(0,0,0,0.05);
--shadow-md:  0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -2px rgba(0,0,0,0.05);
--shadow-lg:  0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -4px rgba(0,0,0,0.05);
--shadow-xl:  0 20px 25px -5px rgba(0,0,0,0.10), 0 8px 10px -6px rgba(0,0,0,0.05);` : `--shadow-sm:  0 2px 4px 0 rgba(0,0,0,0.08);
--shadow-md:  0 8px 16px -2px rgba(0,0,0,0.12);
--shadow-lg:  0 16px 24px -4px rgba(0,0,0,0.14);
--shadow-xl:  0 24px 40px -8px rgba(0,0,0,0.16);`}
\`\`\`

---

## 🌙 Dark mode mapping

\`\`\`css
@media (prefers-color-scheme: dark) {
  :root {
    --color-surface-0:   #18171A;
    --color-surface-1:   #1F1E22;
    --color-surface-2:   #2A2928;
    --color-neutral-800: #D4D3CE;
    --color-neutral-900: #F0EFEA;
    --color-brand:       ${tokens.brand};
  }
}
\`\`\`
`;
}

function buildSkillMd(tokens, name) {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return `---
name: ${slug}
description: Apply the ${name} design system across all frontend projects. Use this skill whenever building React components, HTML/CSS UI, landing pages, dashboards, forms, data tables, modals, navigation, sidebars, tooltips, toasts, or any visual interface. Trigger when the user mentions: components, tokens, spacing, typography, colors, themes, dark mode, buttons, inputs, cards, tables, badges, avatars, skeletons, empty states, accordions, modals, popovers, tabs, pagination, breadcrumbs, steppers, pricing pages, hero sections, or asks to match a brand style.
---

# ${name}

A comprehensive component library and design token system — 57 components across 7 categories. Configured with your exact brand tokens via Design System Studio.

**Brand:** ${tokens.brand} · **Display font:** ${tokens.fontDisplay} · **Radius:** ${tokens.radiusMd} · **Borders:** ${tokens.borderStyle}

---

## First step — always do this

1. Read \`references/tokens.md\` — all colors, spacing, type, shadows, radius
2. Identify which component category is needed (see index below)
3. Read only the relevant reference file

---

## Core principles

1. **Tokens over raw values** — Never hardcode hex or px. Use \`var(--color-brand)\`, \`var(--space-4)\`
2. **Semantic naming** — \`--color-danger\` not \`--color-red\`
3. **Consistent scale** — Only spacing values from the scale
4. **Dark mode by default** — Every component works in both modes
5. **Accessible** — Focus states, ARIA roles, contrast ratios on every interactive component

---

## Component index

| Need | File |
|------|------|
| Button, Input, Textarea, Select, Checkbox, Radio, Toggle, Slider, Search, Dropzone | \`references/components-inputs.md\` |
| Alert, Toast, Modal, Popover, Tooltip, Navbar, Sidebar, Breadcrumbs, Tabs, Pagination | \`references/components-feedback-nav.md\` |
| Table, Avatar, Badge, Progress, Stat card, Skeleton, Empty state, Feed, Accordion, Code block | \`references/components-data-display.md\` |
| Card variants, Divider, Hero, Feature row, Pricing card, Callout, Stepper, Layout utilities | \`references/components-layout.md\` |
| All design tokens | \`references/tokens.md\` |

---

## Quick reference

### Buttons
\`\`\`jsx
<button className="btn btn-primary">Save</button>
<button className="btn btn-secondary">Cancel</button>
<button className="btn btn-ghost">More</button>
<button className="btn btn-danger">Delete</button>
<button className="btn btn-primary btn-sm">Small</button>
<button className="btn btn-primary btn-lg">Large</button>
\`\`\`

### Card
\`\`\`jsx
<div className="card">…</div>
<a href="#" className="card card-interactive">…</a>
\`\`\`

### Badge
\`\`\`jsx
<span className="badge badge-success">Active</span>
<span className="badge badge-warning">Pending</span>
<span className="badge badge-danger">Error</span>
\`\`\`

### Form field
\`\`\`jsx
<div className="field">
  <label className="field-label" htmlFor="x">Label</label>
  <input className="input" id="x" />
  <p className="field-hint">Helper text</p>
</div>
\`\`\`

### Layout
\`\`\`jsx
<div className="page">…</div>
<div className="grid-3">…</div>
<div className="stack">…</div>
<div className="row">…</div>
<div className="row-between">…</div>
\`\`\`

---

## Naming conventions

| Thing | Convention | Example |
|-------|-----------|---------|
| CSS classes | kebab-case | \`.card-title\` |
| React props | camelCase | \`onClick\`, \`isDisabled\` |
| CSS variables | \`--category-descriptor\` | \`--color-brand-light\` |
| Variants | suffix | \`btn-primary\`, \`btn-ghost\` |
| States | \`is-\` prefix | \`is-loading\`, \`is-active\` |

---

## Quality checklist

- [ ] All colors use CSS variables — no hardcoded hex
- [ ] All spacing uses \`--space-*\` tokens
- [ ] Works in light and dark mode
- [ ] Interactive states: hover, focus-visible, disabled
- [ ] Text contrast ≥ 4.5:1 (body), ≥ 3:1 (large text)
- [ ] Mobile breakpoint handled
- [ ] Async components have skeleton + empty + error states
- [ ] All interactive elements have accessible labels / roles
`;
}

export async function exportSkillFile(tokens, name = 'Design System') {
  const zip = new JSZip();
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const root = zip.folder(slug);
  const refs = root.folder('references');

  root.file('SKILL.md', buildSkillMd(tokens, name));
  refs.file('tokens.md', buildTokensMd(tokens, name));

  // Stub references pointing to the full component files
  // In a real setup these would be the full component markdown files
  const componentNote = (name) =>
    `# ${name}\n\nSee the full component library at:\nhttps://github.com/YOUR_USERNAME/design-system-studio\n\nThis file contains the complete CSS + JSX patterns for all ${name.toLowerCase()} components.\nReplace this stub with the full file from the repository.\n`;

  refs.file('components-inputs.md',       componentNote('Input Components'));
  refs.file('components-feedback-nav.md', componentNote('Feedback & Navigation Components'));
  refs.file('components-data-display.md', componentNote('Data Display Components'));
  refs.file('components-layout.md',       componentNote('Layout & Surface Components'));

  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${slug}.skill`);
}

export function exportComponentsCss(tokens, name) {
  const vars = buildCssVars(tokens);
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  const lines = [
    `/* ${name} — Design Tokens`,
    ` * Generated by Design System Studio`,
    ` * Drop this file into your project and import it once at the root.`,
    ` */`,
    ``,
    `:root {`,
    ...Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`),
    `}`,
    ``,
  ].join('\n');

  const blob = new Blob([lines], { type: 'text/css' });
  saveAs(blob, `${slug}-tokens.css`);
}
