import JSZip from 'jszip';
import { saveAs } from 'file-saver';

// ── Token file generators ─────────────────────────────────────────────

function genTokensCss(cssVars, name) {
  const entries = Object.entries(cssVars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');
  return `/* ${name} — Design Tokens
 * Generated by Design System Studio
 * Import once at your app root: import './tokens.css';
 * All component CSS reads these variables — theme changes here cascade everywhere.
 */

:root {
${entries}
}
`;
}

function genTokensJs(cssVars, name) {
  const entries = JSON.stringify(cssVars, null, 2);
  return `// ${name} — Design Tokens (JavaScript)
// Generated by Design System Studio
//
// Usage:
//   import { ds, token, v } from './tokens.js';
//   element.style.setProperty('--ds-brand', ds['--ds-brand']);
//   style={{ color: v('brand') }}

/** All resolved token values — matches what tokens.css outputs */
export const ds = ${entries};

/** Get a raw token value by its full CSS var name */
export const token = (key) => ds[key] ?? '';

/** Build a var(--ds-*) reference string for inline styles */
export const v = (suffix) => \`var(--ds-\${suffix})\`;

export default ds;
`;
}

// ── Component CSS library ─────────────────────────────────────────────

function genComponentsCss(name) {
  return `/* ${name} — Component Library
 * Generated by Design System Studio
 * Requires tokens.css to be imported first.
 *
 * Naming: .ds-[component]  .ds-[component]--[variant]  .ds-[component]--[size]
 * Dark mode is automatic — tokens switch, components follow.
 */

/* ── Reset ──────────────────────────────────────────── */
*, *::before, *::after { box-sizing: border-box; }

/* ══════════════════════════════════════════════════════
   BUTTONS
══════════════════════════════════════════════════════ */
.ds-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  padding: 0 16px;
  height: 36px;
  border-radius: var(--ds-radius-md);
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  font-weight: var(--ds-weight-medium);
  line-height: 1;
  cursor: pointer;
  border: 1px solid transparent;
  transition:
    background var(--ds-transition-fast),
    border-color var(--ds-transition-fast),
    color var(--ds-transition-fast),
    box-shadow var(--ds-transition-fast);
  white-space: nowrap;
  text-decoration: none;
  user-select: none;
  -webkit-tap-highlight-color: transparent;
}
.ds-btn:focus-visible {
  outline: 2px solid var(--ds-brand);
  outline-offset: 2px;
}
.ds-btn:disabled,
.ds-btn.is-loading {
  opacity: 0.5;
  cursor: not-allowed;
  pointer-events: none;
}

/* Sizes */
.ds-btn--xs  { height: 24px; padding: 0 10px; font-size: 11px; border-radius: var(--ds-radius-sm); }
.ds-btn--sm  { height: 30px; padding: 0 12px; font-size: var(--ds-text-xs); }
.ds-btn--lg  { height: 44px; padding: 0 22px; font-size: var(--ds-text-base); }
.ds-btn--xl  { height: 52px; padding: 0 28px; font-size: var(--ds-text-lg); }
.ds-btn--icon { width: 36px; height: 36px; padding: 0; flex-shrink: 0; }
.ds-btn--icon.ds-btn--xs { width: 24px; height: 24px; }
.ds-btn--icon.ds-btn--sm { width: 30px; height: 30px; }
.ds-btn--icon.ds-btn--lg { width: 44px; height: 44px; }
.ds-btn--icon.ds-btn--xl { width: 52px; height: 52px; }

/* Wide / block */
.ds-btn--wide  { width: 100%; }

/* Variants */
.ds-btn--primary {
  background: var(--ds-brand);
  color: var(--ds-brand-hover-text);
  border-color: var(--ds-brand);
}
.ds-btn--primary:hover {
  background: var(--ds-brand-hover);
  border-color: var(--ds-brand-hover);
}

.ds-btn--secondary {
  background: var(--ds-secondary);
  color: var(--ds-secondary-hover-text);
  border-color: var(--ds-secondary);
}
.ds-btn--secondary:hover {
  background: var(--ds-secondary-hover);
  border-color: var(--ds-secondary-hover);
}

.ds-btn--tertiary {
  background: var(--ds-tertiary);
  color: var(--ds-tertiary-hover-text);
  border-color: var(--ds-tertiary);
}
.ds-btn--tertiary:hover {
  background: var(--ds-tertiary-hover);
  border-color: var(--ds-tertiary-hover);
}

.ds-btn--ghost {
  background: transparent;
  color: var(--ds-neutral-800);
  border-color: var(--ds-neutral-200);
}
.ds-btn--ghost:hover {
  background: var(--ds-surface-1);
  border-color: var(--ds-neutral-300);
}

.ds-btn--danger {
  background: var(--ds-danger);
  color: var(--ds-danger-hover-text);
  border-color: var(--ds-danger);
}
.ds-btn--danger:hover {
  background: var(--ds-danger-hover);
  border-color: var(--ds-danger-hover);
}

.ds-btn--success {
  background: var(--ds-success);
  color: var(--ds-success-hover-text);
  border-color: var(--ds-success);
}
.ds-btn--success:hover {
  background: var(--ds-success-hover);
  border-color: var(--ds-success-hover);
}

.ds-btn--link {
  background: transparent;
  color: var(--ds-brand);
  border-color: transparent;
  padding: 0;
  height: auto;
  font-weight: var(--ds-weight-regular);
}
.ds-btn--link:hover {
  color: var(--ds-brand-hover);
  text-decoration: underline;
}

/* Subtle (tinted, low-key) */
.ds-btn--primary-subtle {
  background: color-mix(in srgb, var(--ds-brand) 12%, transparent);
  color: var(--ds-brand);
  border-color: transparent;
}
.ds-btn--primary-subtle:hover {
  background: color-mix(in srgb, var(--ds-brand) 20%, transparent);
}

.ds-btn-icon-slot {
  display: inline-flex;
  align-items: center;
  flex-shrink: 0;
}

/* ══════════════════════════════════════════════════════
   FORM FIELDS
══════════════════════════════════════════════════════ */
.ds-field {
  display: flex;
  flex-direction: column;
  gap: 5px;
  width: 100%;
}
.ds-field-label {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  font-weight: var(--ds-weight-medium);
  color: var(--ds-neutral-800);
  line-height: 1.3;
}
.ds-field-label.is-required::after {
  content: ' *';
  color: var(--ds-danger);
}
.ds-field-hint {
  font-size: var(--ds-text-xs);
  color: var(--ds-neutral-600);
  line-height: 1.5;
}
.ds-field-error {
  font-size: var(--ds-text-xs);
  color: var(--ds-danger);
  line-height: 1.4;
  display: flex;
  align-items: center;
  gap: 4px;
}

/* Input, Textarea, Select */
.ds-input,
.ds-textarea,
.ds-select {
  width: 100%;
  padding: 0 12px;
  height: 36px;
  border-radius: var(--ds-radius-md);
  border: 1px var(--ds-border-style) var(--ds-neutral-200);
  background: var(--ds-surface);
  color: var(--ds-neutral-900);
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  line-height: 1.5;
  transition: border-color var(--ds-transition-fast), box-shadow var(--ds-transition-fast);
  appearance: none;
  -webkit-appearance: none;
}
.ds-input::placeholder,
.ds-textarea::placeholder {
  color: var(--ds-neutral-400);
}
.ds-input:focus,
.ds-textarea:focus,
.ds-select:focus {
  outline: none;
  border-color: var(--ds-brand);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--ds-brand) 15%, transparent);
}
.ds-input:disabled,
.ds-textarea:disabled,
.ds-select:disabled {
  background: var(--ds-surface-1);
  color: var(--ds-neutral-400);
  cursor: not-allowed;
}
.ds-input.is-error,
.ds-textarea.is-error,
.ds-select.is-error {
  border-color: var(--ds-danger);
}
.ds-input.is-error:focus,
.ds-textarea.is-error:focus,
.ds-select.is-error:focus {
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--ds-danger) 15%, transparent);
}

/* Input sizes */
.ds-input--sm { height: 30px; padding: 0 10px; font-size: var(--ds-text-xs); }
.ds-input--lg { height: 44px; padding: 0 14px; font-size: var(--ds-text-base); }

.ds-textarea {
  height: auto;
  min-height: 96px;
  padding: 8px 12px;
  resize: vertical;
}

/* Select */
.ds-select {
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23888' stroke-width='2.5'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 10px center;
  padding-right: 32px;
  cursor: pointer;
}

/* Search input */
.ds-search {
  position: relative;
  display: flex;
  align-items: center;
}
.ds-search-icon {
  position: absolute;
  left: 10px;
  color: var(--ds-neutral-400);
  pointer-events: none;
  display: flex;
  align-items: center;
  z-index: 1;
}
.ds-search .ds-input {
  padding-left: 34px;
}
.ds-search .ds-input--sm {
  padding-left: 30px;
}

/* Input with adornments */
.ds-input-wrap {
  position: relative;
  display: flex;
  align-items: center;
}
.ds-input-prefix,
.ds-input-suffix {
  position: absolute;
  display: flex;
  align-items: center;
  color: var(--ds-neutral-600);
  font-size: var(--ds-text-sm);
  pointer-events: none;
}
.ds-input-prefix { left: 12px; }
.ds-input-suffix { right: 12px; }
.ds-input-wrap .ds-input { padding-left: 36px; }
.ds-input-wrap .ds-input:has(+ .ds-input-suffix) { padding-right: 36px; }

/* Checkbox & Radio */
.ds-checkbox-wrap,
.ds-radio-wrap {
  display: inline-flex;
  align-items: flex-start;
  gap: 8px;
  cursor: pointer;
  user-select: none;
}
.ds-checkbox,
.ds-radio {
  width: 16px;
  height: 16px;
  margin-top: 1px;
  border: 1.5px solid var(--ds-neutral-300);
  background: var(--ds-surface);
  flex-shrink: 0;
  cursor: pointer;
  transition: background var(--ds-transition-fast), border-color var(--ds-transition-fast);
  appearance: none;
  -webkit-appearance: none;
  display: flex;
  align-items: center;
  justify-content: center;
}
.ds-checkbox { border-radius: var(--ds-radius-sm); }
.ds-radio    { border-radius: 50%; }
.ds-checkbox:checked, .ds-radio:checked {
  background: var(--ds-brand);
  border-color: var(--ds-brand);
}
.ds-checkbox:checked::after {
  content: '';
  display: block;
  width: 9px;
  height: 5px;
  border-left: 1.5px solid white;
  border-bottom: 1.5px solid white;
  transform: rotate(-45deg) translate(1px, -1px);
}
.ds-radio:checked::after {
  content: '';
  display: block;
  width: 6px;
  height: 6px;
  background: white;
  border-radius: 50%;
}
.ds-checkbox:focus-visible,
.ds-radio:focus-visible {
  outline: 2px solid var(--ds-brand);
  outline-offset: 2px;
}
.ds-checkbox-label,
.ds-radio-label {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  color: var(--ds-neutral-800);
  line-height: 1.4;
}
.ds-checkbox-desc,
.ds-radio-desc {
  font-size: var(--ds-text-xs);
  color: var(--ds-neutral-600);
  margin-top: 1px;
}

/* Toggle */
.ds-toggle-wrap {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
}
.ds-toggle {
  position: relative;
  width: 36px;
  height: 20px;
  flex-shrink: 0;
}
.ds-toggle input { opacity: 0; width: 0; height: 0; position: absolute; }
.ds-toggle-track {
  position: absolute;
  inset: 0;
  border-radius: var(--ds-radius-pill);
  background: var(--ds-neutral-300);
  transition: background var(--ds-transition-fast);
}
.ds-toggle input:checked + .ds-toggle-track { background: var(--ds-brand); }
.ds-toggle-thumb {
  position: absolute;
  top: 2px;
  left: 2px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: white;
  box-shadow: 0 1px 3px rgba(0,0,0,0.2);
  transition: transform var(--ds-transition-fast);
  pointer-events: none;
}
.ds-toggle input:checked ~ .ds-toggle-thumb { transform: translateX(16px); }
.ds-toggle input:focus-visible + .ds-toggle-track {
  outline: 2px solid var(--ds-brand);
  outline-offset: 2px;
}
.ds-toggle-label {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  color: var(--ds-neutral-800);
}

/* ══════════════════════════════════════════════════════
   BADGE
══════════════════════════════════════════════════════ */
.ds-badge {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 0 7px;
  height: 20px;
  border-radius: var(--ds-radius-sm);
  font-family: var(--ds-font-body);
  font-size: 11px;
  font-weight: var(--ds-weight-semibold);
  line-height: 1;
  letter-spacing: var(--ds-tracking-wide);
  border: 1px solid transparent;
  white-space: nowrap;
}
.ds-badge--sm  { height: 16px; padding: 0 5px; font-size: 9px; }
.ds-badge--lg  { height: 24px; padding: 0 10px; font-size: var(--ds-text-xs); }
.ds-badge--pill { border-radius: var(--ds-radius-pill); }

/* Filled (default) */
.ds-badge--primary { background: var(--ds-brand); color: var(--ds-brand-hover-text); }
.ds-badge--success { background: var(--ds-success); color: var(--ds-success-hover-text); }
.ds-badge--warning { background: var(--ds-warning); color: var(--ds-warning-hover-text); }
.ds-badge--danger  { background: var(--ds-danger);  color: var(--ds-danger-hover-text);  }
.ds-badge--info    { background: var(--ds-info);    color: var(--ds-info-hover-text);    }
.ds-badge--neutral { background: var(--ds-neutral-200); color: var(--ds-neutral-800); }

/* Subtle — tinted, low contrast */
.ds-badge--success.ds-badge--subtle { background: var(--ds-success-subtle); color: var(--ds-success-on-subtle); }
.ds-badge--warning.ds-badge--subtle { background: var(--ds-warning-subtle); color: var(--ds-warning-on-subtle); }
.ds-badge--danger.ds-badge--subtle  { background: var(--ds-danger-subtle);  color: var(--ds-danger-on-subtle);  }
.ds-badge--info.ds-badge--subtle    { background: var(--ds-info-subtle);    color: var(--ds-info-on-subtle);    }
.ds-badge--primary.ds-badge--subtle {
  background: color-mix(in srgb, var(--ds-brand) 12%, transparent);
  color: var(--ds-brand);
}

/* Outline */
.ds-badge--outline {
  background: transparent;
}
.ds-badge--success.ds-badge--outline { color: var(--ds-success); border-color: var(--ds-success); }
.ds-badge--warning.ds-badge--outline { color: var(--ds-warning); border-color: var(--ds-warning); }
.ds-badge--danger.ds-badge--outline  { color: var(--ds-danger);  border-color: var(--ds-danger);  }
.ds-badge--info.ds-badge--outline    { color: var(--ds-info);    border-color: var(--ds-info);    }
.ds-badge--primary.ds-badge--outline { color: var(--ds-brand);   border-color: var(--ds-brand);   }

.ds-badge-dot {
  width: 6px; height: 6px; border-radius: 50%; background: currentColor; flex-shrink: 0;
}

/* ══════════════════════════════════════════════════════
   ALERT
══════════════════════════════════════════════════════ */
.ds-alert {
  display: flex;
  gap: 12px;
  padding: 14px 16px;
  border-radius: var(--ds-radius-lg);
  border: 1px solid transparent;
  font-family: var(--ds-font-body);
}
.ds-alert--success {
  background: var(--ds-success-subtle);
  border-color: color-mix(in srgb, var(--ds-success) 30%, transparent);
  color: var(--ds-success-on-subtle);
}
.ds-alert--warning {
  background: var(--ds-warning-subtle);
  border-color: color-mix(in srgb, var(--ds-warning) 30%, transparent);
  color: var(--ds-warning-on-subtle);
}
.ds-alert--danger {
  background: var(--ds-danger-subtle);
  border-color: color-mix(in srgb, var(--ds-danger) 30%, transparent);
  color: var(--ds-danger-on-subtle);
}
.ds-alert--info {
  background: var(--ds-info-subtle);
  border-color: color-mix(in srgb, var(--ds-info) 30%, transparent);
  color: var(--ds-info-on-subtle);
}
.ds-alert-icon { flex-shrink: 0; margin-top: 1px; }
.ds-alert-body {
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 3px;
}
.ds-alert-title {
  font-size: var(--ds-text-sm);
  font-weight: var(--ds-weight-semibold);
  line-height: 1.4;
}
.ds-alert-desc {
  font-size: var(--ds-text-sm);
  opacity: 0.85;
  line-height: 1.5;
}
.ds-alert-close {
  flex-shrink: 0;
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 2px;
  border-radius: var(--ds-radius-sm);
  color: currentColor;
  opacity: 0.6;
  display: flex;
  align-items: center;
  margin-top: -2px;
  transition: opacity var(--ds-transition-fast);
}
.ds-alert-close:hover { opacity: 1; }

/* Callout — left-bordered variant */
.ds-callout {
  padding: 14px 18px;
  border-radius: var(--ds-radius-md);
  border-left: 4px solid;
  font-family: var(--ds-font-body);
}
.ds-callout--info    { background: var(--ds-info-subtle);    border-color: var(--ds-info);    color: var(--ds-info-on-subtle); }
.ds-callout--success { background: var(--ds-success-subtle); border-color: var(--ds-success); color: var(--ds-success-on-subtle); }
.ds-callout--warning { background: var(--ds-warning-subtle); border-color: var(--ds-warning); color: var(--ds-warning-on-subtle); }
.ds-callout--danger  { background: var(--ds-danger-subtle);  border-color: var(--ds-danger);  color: var(--ds-danger-on-subtle); }
.ds-callout-title  { font-weight: var(--ds-weight-semibold); font-size: var(--ds-text-sm); margin-bottom: 3px; }
.ds-callout-body   { font-size: var(--ds-text-sm); opacity: 0.9; line-height: 1.5; }

/* ══════════════════════════════════════════════════════
   CARD
══════════════════════════════════════════════════════ */
.ds-card {
  background: var(--ds-surface);
  border: 1px var(--ds-border-style) var(--ds-neutral-200);
  border-radius: var(--ds-radius-lg);
  box-shadow: var(--ds-shadow-1);
  overflow: hidden;
}
.ds-card--bordered { box-shadow: none; }
.ds-card--ghost {
  background: var(--ds-surface-1);
  border-color: transparent;
  box-shadow: none;
}
.ds-card--elevated {
  box-shadow: var(--ds-shadow-3);
  border-color: transparent;
}
.ds-card--interactive {
  cursor: pointer;
  transition: box-shadow var(--ds-transition-base), transform var(--ds-transition-base), border-color var(--ds-transition-base);
  text-decoration: none;
  display: block;
  color: inherit;
}
.ds-card--interactive:hover {
  box-shadow: var(--ds-shadow-3);
  border-color: var(--ds-neutral-300);
  transform: translateY(-1px);
}
.ds-card--interactive:focus-visible {
  outline: 2px solid var(--ds-brand);
  outline-offset: 2px;
}
.ds-card-header {
  padding: 16px 20px;
  border-bottom: 1px var(--ds-border-style) var(--ds-neutral-200);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-shrink: 0;
}
.ds-card-title {
  font-family: var(--ds-font-display);
  font-size: var(--ds-text-base);
  font-weight: var(--ds-weight-semibold);
  color: var(--ds-neutral-900);
  line-height: 1.3;
}
.ds-card-subtitle {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-xs);
  color: var(--ds-neutral-600);
  margin-top: 2px;
  line-height: 1.4;
}
.ds-card-body { padding: 20px; }
.ds-card-footer {
  padding: 12px 20px;
  border-top: 1px var(--ds-border-style) var(--ds-neutral-200);
  background: var(--ds-surface-1);
  display: flex;
  align-items: center;
  gap: 8px;
}

/* ══════════════════════════════════════════════════════
   TABS  (3 style variants)
══════════════════════════════════════════════════════ */

/* Variant 1 — Line (underline) - default */
.ds-tab-list {
  display: flex;
  border-bottom: 1.5px solid var(--ds-neutral-200);
}
.ds-tab {
  padding: 8px 16px;
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  font-weight: var(--ds-weight-medium);
  color: var(--ds-neutral-600);
  border: none;
  background: transparent;
  cursor: pointer;
  border-bottom: 2px solid transparent;
  margin-bottom: -1.5px;
  transition: color var(--ds-transition-fast), border-color var(--ds-transition-fast);
  white-space: nowrap;
  display: inline-flex;
  align-items: center;
  gap: 6px;
}
.ds-tab:hover { color: var(--ds-neutral-800); }
.ds-tab.is-active {
  color: var(--ds-brand);
  border-bottom-color: var(--ds-brand);
}
.ds-tab:focus-visible {
  outline: 2px solid var(--ds-brand);
  outline-offset: -2px;
  border-radius: var(--ds-radius-sm) var(--ds-radius-sm) 0 0;
}
.ds-tab:disabled { opacity: 0.4; cursor: not-allowed; }
.ds-tab-panel { padding: 20px 0; }
.ds-tab-count {
  background: var(--ds-neutral-200);
  color: var(--ds-neutral-600);
  font-size: 10px;
  font-weight: var(--ds-weight-semibold);
  padding: 1px 5px;
  border-radius: var(--ds-radius-pill);
  line-height: 16px;
}
.ds-tab.is-active .ds-tab-count {
  background: color-mix(in srgb, var(--ds-brand) 15%, transparent);
  color: var(--ds-brand);
}

/* Variant 2 — Pill */
.ds-tabs--pill .ds-tab-list {
  border-bottom: none;
  background: var(--ds-surface-1);
  padding: 4px;
  border-radius: var(--ds-radius-pill);
  gap: 2px;
  display: inline-flex;
}
.ds-tabs--pill .ds-tab {
  border-radius: var(--ds-radius-pill);
  border-bottom: none;
  margin-bottom: 0;
}
.ds-tabs--pill .ds-tab:hover { background: var(--ds-surface-2); }
.ds-tabs--pill .ds-tab.is-active {
  background: var(--ds-brand);
  color: var(--ds-brand-hover-text);
  box-shadow: 0 1px 3px rgba(0,0,0,.15);
  border-bottom-color: transparent;
}

/* Variant 3 — Boxed */
.ds-tabs--boxed .ds-tab-list {
  border-bottom: 1.5px solid var(--ds-neutral-200);
  gap: 4px;
}
.ds-tabs--boxed .ds-tab {
  border-radius: var(--ds-radius-md) var(--ds-radius-md) 0 0;
  border: 1px solid transparent;
  border-bottom: none;
  margin-bottom: -1.5px;
}
.ds-tabs--boxed .ds-tab:hover {
  background: var(--ds-surface-1);
  border-color: var(--ds-neutral-200);
  border-bottom-color: transparent;
}
.ds-tabs--boxed .ds-tab.is-active {
  background: var(--ds-surface);
  color: var(--ds-neutral-900);
  border-color: var(--ds-neutral-200);
  border-bottom-color: var(--ds-surface);
}
.ds-tabs--boxed .ds-tab-panel {
  border: 1px solid var(--ds-neutral-200);
  border-top: none;
  border-radius: 0 var(--ds-radius-md) var(--ds-radius-md) var(--ds-radius-md);
  padding: 20px;
}

/* ══════════════════════════════════════════════════════
   MODAL
══════════════════════════════════════════════════════ */
.ds-modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(2px);
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  z-index: var(--ds-z-modal);
  animation: ds-fade-in 120ms ease;
}
.ds-modal {
  background: var(--ds-surface);
  border: 1px solid var(--ds-neutral-200);
  border-radius: var(--ds-radius-lg);
  box-shadow: var(--ds-shadow-5);
  width: 100%;
  max-width: 480px;
  max-height: calc(100dvh - 48px);
  display: flex;
  flex-direction: column;
  overflow: hidden;
  animation: ds-modal-in var(--ds-duration-base) var(--ds-ease-enter);
}
@keyframes ds-fade-in {
  from { opacity: 0; }
  to   { opacity: 1; }
}
@keyframes ds-modal-in {
  from { opacity: 0; transform: scale(0.96) translateY(8px); }
  to   { opacity: 1; transform: scale(1) translateY(0); }
}
.ds-modal--sm { max-width: 360px; }
.ds-modal--lg { max-width: 640px; }
.ds-modal--xl { max-width: 860px; }
.ds-modal-header {
  padding: 20px 24px 16px;
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 12px;
  border-bottom: 1px solid var(--ds-neutral-200);
  flex-shrink: 0;
}
.ds-modal-title {
  font-family: var(--ds-font-display);
  font-size: var(--ds-text-lg);
  font-weight: var(--ds-weight-semibold);
  color: var(--ds-neutral-900);
  line-height: 1.3;
}
.ds-modal-subtitle {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  color: var(--ds-neutral-600);
  margin-top: 3px;
  line-height: 1.4;
}
.ds-modal-close {
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 4px;
  border-radius: var(--ds-radius-sm);
  color: var(--ds-neutral-600);
  display: flex;
  align-items: center;
  transition: color var(--ds-transition-fast), background var(--ds-transition-fast);
  flex-shrink: 0;
  margin-top: -2px;
}
.ds-modal-close:hover {
  background: var(--ds-surface-1);
  color: var(--ds-neutral-900);
}
.ds-modal-body {
  padding: 20px 24px;
  overflow-y: auto;
  flex: 1;
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  color: var(--ds-neutral-800);
  line-height: var(--ds-leading-normal);
}
.ds-modal-footer {
  padding: 16px 24px;
  border-top: 1px solid var(--ds-neutral-200);
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 8px;
  flex-shrink: 0;
  background: var(--ds-surface-1);
}

/* ══════════════════════════════════════════════════════
   AVATAR
══════════════════════════════════════════════════════ */
.ds-avatar {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  position: relative;
  width: 36px;
  height: 36px;
  border-radius: 50%;
  background: color-mix(in srgb, var(--ds-brand) 15%, transparent);
  color: var(--ds-brand);
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-xs);
  font-weight: var(--ds-weight-semibold);
  flex-shrink: 0;
  overflow: visible;
  text-transform: uppercase;
}
.ds-avatar--xs  { width: 20px; height: 20px; font-size: 9px; }
.ds-avatar--sm  { width: 28px; height: 28px; font-size: 11px; }
.ds-avatar--lg  { width: 48px; height: 48px; font-size: var(--ds-text-sm); }
.ds-avatar--xl  { width: 64px; height: 64px; font-size: var(--ds-text-base); }
.ds-avatar--2xl { width: 96px; height: 96px; font-size: var(--ds-text-xl); }
.ds-avatar--square { border-radius: var(--ds-radius-md); }
.ds-avatar-img {
  width: 100%; height: 100%;
  border-radius: inherit;
  object-fit: cover;
}
.ds-avatar-status {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 10px;
  height: 10px;
  border-radius: 50%;
  border: 2px solid var(--ds-surface);
}
.ds-avatar--lg  .ds-avatar-status { width: 12px; height: 12px; }
.ds-avatar--xl  .ds-avatar-status { width: 14px; height: 14px; }
.ds-avatar--2xl .ds-avatar-status { width: 18px; height: 18px; }
.ds-avatar-status--online  { background: var(--ds-success); }
.ds-avatar-status--away    { background: var(--ds-warning); }
.ds-avatar-status--busy    { background: var(--ds-danger); }
.ds-avatar-status--offline { background: var(--ds-neutral-400); }
.ds-avatar-group { display: flex; }
.ds-avatar-group .ds-avatar { margin-left: -8px; border: 2px solid var(--ds-surface); }
.ds-avatar-group .ds-avatar:first-child { margin-left: 0; }

/* ══════════════════════════════════════════════════════
   TABLE
══════════════════════════════════════════════════════ */
.ds-table-wrap {
  overflow-x: auto;
  border: 1px solid var(--ds-neutral-200);
  border-radius: var(--ds-radius-lg);
  box-shadow: var(--ds-shadow-1);
}
.ds-table {
  width: 100%;
  border-collapse: collapse;
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-sm);
  color: var(--ds-neutral-800);
}
.ds-table th {
  padding: 10px 16px;
  text-align: left;
  font-size: var(--ds-text-xs);
  font-weight: var(--ds-weight-semibold);
  color: var(--ds-neutral-600);
  letter-spacing: var(--ds-tracking-wide);
  text-transform: uppercase;
  background: var(--ds-surface-1);
  border-bottom: 1.5px solid var(--ds-neutral-200);
  white-space: nowrap;
}
.ds-table td {
  padding: 13px 16px;
  border-bottom: 1px solid var(--ds-neutral-200);
  vertical-align: middle;
  color: var(--ds-neutral-800);
}
.ds-table tbody tr:last-child td { border-bottom: none; }
.ds-table--striped tbody tr:nth-child(even) td { background: var(--ds-surface-1); }
.ds-table--hoverable tbody tr { transition: background var(--ds-transition-fast); }
.ds-table--hoverable tbody tr:hover td {
  background: color-mix(in srgb, var(--ds-brand) 5%, transparent);
}
.ds-table--bordered td,
.ds-table--bordered th { border-right: 1px solid var(--ds-neutral-200); }
.ds-table--bordered td:last-child,
.ds-table--bordered th:last-child { border-right: none; }
.ds-table--compact th { padding: 7px 12px; }
.ds-table--compact td { padding: 9px 12px; }
.ds-th-sortable { cursor: pointer; user-select: none; }
.ds-th-sortable:hover { background: var(--ds-surface-2) !important; }
.ds-sort-icon { opacity: 0.35; margin-left: 5px; display: inline-block; }
.ds-th-sortable.is-sorted .ds-sort-icon { opacity: 1; color: var(--ds-brand); }

/* ══════════════════════════════════════════════════════
   SPINNER & PROGRESS
══════════════════════════════════════════════════════ */
.ds-spinner {
  display: inline-block;
  width: 20px;
  height: 20px;
  border: 2px solid color-mix(in srgb, var(--ds-brand) 25%, transparent);
  border-top-color: var(--ds-brand);
  border-radius: 50%;
  animation: ds-spin 0.7s linear infinite;
  flex-shrink: 0;
}
@keyframes ds-spin { to { transform: rotate(360deg); } }
.ds-spinner--xs { width: 12px; height: 12px; border-width: 1.5px; }
.ds-spinner--sm { width: 16px; height: 16px; }
.ds-spinner--lg { width: 32px; height: 32px; border-width: 3px; }
.ds-spinner--xl { width: 48px; height: 48px; border-width: 4px; }
.ds-spinner--muted {
  border-color: color-mix(in srgb, currentColor 20%, transparent);
  border-top-color: currentColor;
}

.ds-progress {
  width: 100%;
  height: 6px;
  background: var(--ds-neutral-200);
  border-radius: var(--ds-radius-pill);
  overflow: hidden;
}
.ds-progress--sm { height: 4px; }
.ds-progress--lg { height: 10px; }
.ds-progress-bar {
  height: 100%;
  background: var(--ds-brand);
  border-radius: var(--ds-radius-pill);
  transition: width var(--ds-transition-slow);
}
.ds-progress-bar--success { background: var(--ds-success); }
.ds-progress-bar--warning { background: var(--ds-warning); }
.ds-progress-bar--danger  { background: var(--ds-danger); }

/* ══════════════════════════════════════════════════════
   SKELETON
══════════════════════════════════════════════════════ */
.ds-skeleton {
  border-radius: var(--ds-radius-md);
  background: linear-gradient(90deg,
    var(--ds-neutral-200) 0%,
    var(--ds-surface-2) 40%,
    var(--ds-neutral-200) 80%
  );
  background-size: 200% 100%;
  animation: ds-shimmer 1.6s ease infinite;
}
@keyframes ds-shimmer {
  0%   { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
.ds-skeleton--text   { height: 14px; border-radius: var(--ds-radius-sm); }
.ds-skeleton--title  { height: 20px; width: 55%; border-radius: var(--ds-radius-sm); }
.ds-skeleton--avatar { border-radius: 50%; }

/* ══════════════════════════════════════════════════════
   EMPTY STATE
══════════════════════════════════════════════════════ */
.ds-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 48px 24px;
  gap: 10px;
  font-family: var(--ds-font-body);
}
.ds-empty-icon   { color: var(--ds-neutral-400); margin-bottom: 4px; }
.ds-empty-title  { font-family: var(--ds-font-display); font-size: var(--ds-text-base); font-weight: var(--ds-weight-semibold); color: var(--ds-neutral-900); line-height: 1.3; }
.ds-empty-desc   { font-size: var(--ds-text-sm); color: var(--ds-neutral-600); line-height: 1.5; max-width: 320px; }

/* ══════════════════════════════════════════════════════
   TOOLTIP
══════════════════════════════════════════════════════ */
.ds-tooltip-wrap { position: relative; display: inline-flex; align-items: center; }
.ds-tooltip {
  position: absolute;
  bottom: calc(100% + 8px);
  left: 50%;
  transform: translateX(-50%);
  background: var(--ds-neutral-900);
  color: var(--ds-surface);
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-xs);
  padding: 5px 9px;
  border-radius: var(--ds-radius-md);
  white-space: nowrap;
  pointer-events: none;
  opacity: 0;
  transition: opacity var(--ds-transition-fast);
  z-index: var(--ds-z-tooltip);
}
.ds-tooltip::after {
  content: '';
  position: absolute;
  top: 100%;
  left: 50%;
  transform: translateX(-50%);
  border: 5px solid transparent;
  border-top-color: var(--ds-neutral-900);
}
.ds-tooltip-wrap:hover .ds-tooltip { opacity: 1; }

/* ══════════════════════════════════════════════════════
   DIVIDER
══════════════════════════════════════════════════════ */
.ds-divider {
  height: 1px;
  background: var(--ds-neutral-200);
  border: none;
  margin: 0;
}
.ds-divider--vertical {
  width: 1px; height: auto; align-self: stretch;
}

/* ══════════════════════════════════════════════════════
   LAYOUT UTILITIES
══════════════════════════════════════════════════════ */
.ds-stack     { display: flex; flex-direction: column; gap: var(--ds-space-md); }
.ds-stack--xs { gap: var(--ds-space-xs); }
.ds-stack--sm { gap: var(--ds-space-sm); }
.ds-stack--lg { gap: var(--ds-space-lg); }
.ds-stack--xl { gap: var(--ds-space-xl); }

.ds-row         { display: flex; align-items: center; gap: var(--ds-space-sm); }
.ds-row--center  { justify-content: center; }
.ds-row--between { justify-content: space-between; }
.ds-row--end     { justify-content: flex-end; }
.ds-row--wrap    { flex-wrap: wrap; }

.ds-grid    { display: grid; gap: var(--ds-space-md); }
.ds-grid--2 { grid-template-columns: repeat(2, 1fr); }
.ds-grid--3 { grid-template-columns: repeat(3, 1fr); }
.ds-grid--4 { grid-template-columns: repeat(4, 1fr); }
.ds-grid--auto { grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); }

@media (max-width: 640px) {
  .ds-grid--2, .ds-grid--3, .ds-grid--4 { grid-template-columns: 1fr; }
}
@media (max-width: 900px) {
  .ds-grid--3, .ds-grid--4 { grid-template-columns: repeat(2, 1fr); }
}

/* Stat card */
.ds-stat {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 18px 20px;
}
.ds-stat-label {
  font-family: var(--ds-font-body);
  font-size: var(--ds-text-xs);
  font-weight: var(--ds-weight-medium);
  color: var(--ds-neutral-600);
  text-transform: uppercase;
  letter-spacing: var(--ds-tracking-wide);
}
.ds-stat-value {
  font-family: var(--ds-font-display);
  font-size: var(--ds-text-2xl);
  font-weight: var(--ds-weight-bold);
  color: var(--ds-neutral-900);
  line-height: 1.1;
}
.ds-stat-change {
  font-size: var(--ds-text-xs);
  font-family: var(--ds-font-body);
  display: flex;
  align-items: center;
  gap: 3px;
}
.ds-stat-change--up   { color: var(--ds-success); }
.ds-stat-change--down { color: var(--ds-danger); }
`;
}

// ── React component generators ────────────────────────────────────────

function genButtonJsx() {
  return `import { forwardRef } from 'react';

/**
 * @param {{
 *   variant?: 'primary'|'secondary'|'tertiary'|'ghost'|'danger'|'success'|'link'|'primary-subtle',
 *   size?: 'xs'|'sm'|'md'|'lg'|'xl',
 *   loading?: boolean,
 *   leftIcon?: React.ReactNode,
 *   rightIcon?: React.ReactNode,
 *   wide?: boolean,
 *   className?: string,
 * } & React.ButtonHTMLAttributes<HTMLButtonElement>} props
 */
export const Button = forwardRef(function Button(
  { variant = 'primary', size = 'md', loading = false, leftIcon, rightIcon, wide, children, className = '', ...rest },
  ref
) {
  const cls = [
    'ds-btn',
    'ds-btn--' + variant,
    size !== 'md' ? 'ds-btn--' + size : '',
    !children && (leftIcon || rightIcon) ? 'ds-btn--icon' : '',
    wide ? 'ds-btn--wide' : '',
    loading ? 'is-loading' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <button ref={ref} className={cls} disabled={rest.disabled || loading} {...rest}>
      {loading && <span className="ds-spinner ds-spinner--xs ds-spinner--muted" aria-hidden="true" />}
      {!loading && leftIcon && <span className="ds-btn-icon-slot">{leftIcon}</span>}
      {children}
      {rightIcon && <span className="ds-btn-icon-slot">{rightIcon}</span>}
    </button>
  );
});

/** Horizontal button group with consistent spacing */
export function ButtonGroup({ children, className = '' }) {
  return <div className={'ds-row ' + className}>{children}</div>;
}
`;
}

function genInputJsx() {
  return `import { forwardRef, useId } from 'react';

/**
 * Field wrapper — label + input + hint + error
 */
export function Field({ label, hint, error, required, htmlFor, children, className = '' }) {
  return (
    <div className={'ds-field ' + className}>
      {label && (
        <label className={'ds-field-label' + (required ? ' is-required' : '')} htmlFor={htmlFor}>
          {label}
        </label>
      )}
      {children}
      {error  && <span className="ds-field-error">{error}</span>}
      {!error && hint && <span className="ds-field-hint">{hint}</span>}
    </div>
  );
}

/**
 * @param {{ size?: 'sm'|'md'|'lg', error?: boolean, className?: string } & React.InputHTMLAttributes<HTMLInputElement>} props
 */
export const Input = forwardRef(function Input(
  { size = 'md', error, className = '', ...rest },
  ref
) {
  const cls = [
    'ds-input',
    size !== 'md' ? 'ds-input--' + size : '',
    error ? 'is-error' : '',
    className,
  ].filter(Boolean).join(' ');
  return <input ref={ref} className={cls} {...rest} />;
});

/**
 * @param {{ error?: boolean, className?: string } & React.TextareaHTMLAttributes<HTMLTextAreaElement>} props
 */
export const Textarea = forwardRef(function Textarea(
  { error, className = '', ...rest },
  ref
) {
  return (
    <textarea
      ref={ref}
      className={'ds-textarea' + (error ? ' is-error' : '') + (className ? ' ' + className : '')}
      {...rest}
    />
  );
});

/**
 * @param {{ size?: 'sm'|'md'|'lg', error?: boolean, className?: string } & React.SelectHTMLAttributes<HTMLSelectElement>} props
 */
export const Select = forwardRef(function Select(
  { size = 'md', error, className = '', children, ...rest },
  ref
) {
  const cls = [
    'ds-select',
    size !== 'md' ? 'ds-select--' + size : '',
    error ? 'is-error' : '',
    className,
  ].filter(Boolean).join(' ');
  return <select ref={ref} className={cls} {...rest}>{children}</select>;
});

/** Search input with icon slot */
export function SearchInput({ icon, className = '', ...rest }) {
  return (
    <div className={'ds-search ' + className}>
      <span className="ds-search-icon" aria-hidden="true">
        {icon || (
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>
          </svg>
        )}
      </span>
      <input className="ds-input" {...rest} />
    </div>
  );
}

/** Checkbox with label */
export function Checkbox({ label, description, id: idProp, className = '', ...rest }) {
  const autoId = useId();
  const id = idProp || autoId;
  return (
    <label className={'ds-checkbox-wrap ' + className} htmlFor={id}>
      <input type="checkbox" className="ds-checkbox" id={id} {...rest} />
      {label && (
        <span>
          <span className="ds-checkbox-label">{label}</span>
          {description && <span className="ds-checkbox-desc">{description}</span>}
        </span>
      )}
    </label>
  );
}

/** Radio with label */
export function Radio({ label, description, id: idProp, className = '', ...rest }) {
  const autoId = useId();
  const id = idProp || autoId;
  return (
    <label className={'ds-radio-wrap ' + className} htmlFor={id}>
      <input type="radio" className="ds-radio" id={id} {...rest} />
      {label && (
        <span>
          <span className="ds-radio-label">{label}</span>
          {description && <span className="ds-radio-desc">{description}</span>}
        </span>
      )}
    </label>
  );
}

/** Toggle switch */
export function Toggle({ label, id: idProp, className = '', ...rest }) {
  const autoId = useId();
  const id = idProp || autoId;
  return (
    <label className={'ds-toggle-wrap ' + className} htmlFor={id}>
      <span className="ds-toggle">
        <input type="checkbox" id={id} {...rest} />
        <span className="ds-toggle-track" />
        <span className="ds-toggle-thumb" />
      </span>
      {label && <span className="ds-toggle-label">{label}</span>}
    </label>
  );
}
`;
}

function genBadgeJsx() {
  return `/**
 * @param {{
 *   variant?: 'primary'|'success'|'warning'|'danger'|'info'|'neutral',
 *   style?: 'filled'|'subtle'|'outline',
 *   size?: 'sm'|'md'|'lg',
 *   pill?: boolean,
 *   dot?: boolean,
 *   className?: string,
 * } & React.HTMLAttributes<HTMLSpanElement>} props
 */
export function Badge({
  variant = 'primary',
  style: styleVariant = 'filled',
  size = 'md',
  pill = false,
  dot = false,
  children,
  className = '',
  ...rest
}) {
  const cls = [
    'ds-badge',
    'ds-badge--' + variant,
    styleVariant !== 'filled' ? 'ds-badge--' + styleVariant : '',
    size !== 'md' ? 'ds-badge--' + size : '',
    pill ? 'ds-badge--pill' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <span className={cls} {...rest}>
      {dot && <span className="ds-badge-dot" aria-hidden="true" />}
      {children}
    </span>
  );
}
`;
}

function genAlertJsx() {
  return `import { useState } from 'react';

const ICONS = {
  success: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/>
    </svg>
  ),
  warning: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/>
      <path d="M12 9v4"/><path d="M12 17h.01"/>
    </svg>
  ),
  danger: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
      <circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>
    </svg>
  ),
  info: (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
      <circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/>
    </svg>
  ),
};

/**
 * @param {{
 *   variant: 'success'|'warning'|'danger'|'info',
 *   title?: string,
 *   dismissible?: boolean,
 *   icon?: React.ReactNode | false,
 *   className?: string,
 * } & React.HTMLAttributes<HTMLDivElement>} props
 */
export function Alert({ variant = 'info', title, dismissible = false, icon, children, className = '', onDismiss, ...rest }) {
  const [dismissed, setDismissed] = useState(false);
  if (dismissed) return null;

  const handleDismiss = () => {
    setDismissed(true);
    onDismiss?.();
  };

  return (
    <div className={'ds-alert ds-alert--' + variant + (className ? ' ' + className : '')} role="alert" {...rest}>
      {icon !== false && (
        <span className="ds-alert-icon" aria-hidden="true">
          {icon || ICONS[variant]}
        </span>
      )}
      <div className="ds-alert-body">
        {title && <div className="ds-alert-title">{title}</div>}
        {children && <div className="ds-alert-desc">{children}</div>}
      </div>
      {dismissible && (
        <button className="ds-alert-close" onClick={handleDismiss} aria-label="Dismiss">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <path d="M18 6 6 18"/><path d="m6 6 12 12"/>
          </svg>
        </button>
      )}
    </div>
  );
}

/**
 * Callout — left-bordered informational block
 */
export function Callout({ variant = 'info', title, children, className = '' }) {
  return (
    <div className={'ds-callout ds-callout--' + variant + (className ? ' ' + className : '')}>
      {title && <div className="ds-callout-title">{title}</div>}
      <div className="ds-callout-body">{children}</div>
    </div>
  );
}
`;
}

function genCardJsx() {
  return `/**
 * @param {{
 *   variant?: 'default'|'bordered'|'ghost'|'elevated'|'interactive',
 *   className?: string,
 * } & React.HTMLAttributes<HTMLDivElement>} props
 */
export function Card({ variant = 'default', children, className = '', ...rest }) {
  const tag = variant === 'interactive' && rest.href ? 'a' : 'div';
  const cls = [
    'ds-card',
    variant !== 'default' ? 'ds-card--' + variant : '',
    className,
  ].filter(Boolean).join(' ');

  const Tag = tag;
  return <Tag className={cls} {...rest}>{children}</Tag>;
}

export function CardHeader({ children, className = '', ...rest }) {
  return <div className={'ds-card-header ' + className} {...rest}>{children}</div>;
}

export function CardTitle({ children, className = '', ...rest }) {
  return <div className={'ds-card-title ' + className} {...rest}>{children}</div>;
}

export function CardSubtitle({ children, className = '', ...rest }) {
  return <div className={'ds-card-subtitle ' + className} {...rest}>{children}</div>;
}

export function CardBody({ children, className = '', ...rest }) {
  return <div className={'ds-card-body ' + className} {...rest}>{children}</div>;
}

export function CardFooter({ children, className = '', ...rest }) {
  return <div className={'ds-card-footer ' + className} {...rest}>{children}</div>;
}

/** Stat card — number highlight with label and optional trend */
export function StatCard({ label, value, change, changeDir = 'up', suffix, children, className = '' }) {
  return (
    <div className={'ds-card ds-stat ' + className}>
      <div className="ds-stat-label">{label}</div>
      <div className="ds-stat-value">{value}{suffix && <span style={{fontSize:'0.6em',fontWeight:400,marginLeft:4}}>{suffix}</span>}</div>
      {change && (
        <div className={'ds-stat-change ds-stat-change--' + changeDir}>
          {changeDir === 'up' ? '▲' : '▼'} {change}
        </div>
      )}
      {children}
    </div>
  );
}
`;
}

function genTabsJsx() {
  return `import { useState, createContext, useContext } from 'react';

const TabsCtx = createContext({ active: '', setActive: () => {} });

/**
 * Tabs container — manages active state
 * @param {{
 *   defaultValue?: string,
 *   value?: string,
 *   onChange?: (val: string) => void,
 *   variant?: 'line'|'pill'|'boxed',
 *   className?: string,
 * }} props
 */
export function Tabs({ defaultValue, value, onChange, variant = 'line', children, className = '' }) {
  const [internal, setInternal] = useState(defaultValue || '');
  const active = value !== undefined ? value : internal;
  const setActive = (v) => {
    setInternal(v);
    onChange?.(v);
  };

  const cls = [
    'ds-tabs',
    variant !== 'line' ? 'ds-tabs--' + variant : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <TabsCtx.Provider value={{ active, setActive }}>
      <div className={cls}>{children}</div>
    </TabsCtx.Provider>
  );
}

/** Tab list — horizontal row of tab triggers */
export function TabList({ children, className = '' }) {
  return (
    <div className={'ds-tab-list ' + className} role="tablist">
      {children}
    </div>
  );
}

/**
 * Individual tab trigger
 * @param {{ value: string, disabled?: boolean, count?: number, icon?: React.ReactNode, className?: string }} props
 */
export function Tab({ value, disabled, count, icon, children, className = '' }) {
  const { active, setActive } = useContext(TabsCtx);
  const isActive = active === value;

  return (
    <button
      className={'ds-tab' + (isActive ? ' is-active' : '') + (className ? ' ' + className : '')}
      role="tab"
      aria-selected={isActive}
      disabled={disabled}
      onClick={() => !disabled && setActive(value)}
    >
      {icon && <span aria-hidden="true">{icon}</span>}
      {children}
      {count !== undefined && <span className="ds-tab-count">{count}</span>}
    </button>
  );
}

/**
 * Tab panel — shown when its value matches the active tab
 * @param {{ value: string, className?: string }} props
 */
export function TabPanel({ value, children, className = '' }) {
  const { active } = useContext(TabsCtx);
  if (active !== value) return null;
  return (
    <div className={'ds-tab-panel ' + className} role="tabpanel">
      {children}
    </div>
  );
}
`;
}

function genModalJsx() {
  return `import { useEffect, useRef } from 'react';

/**
 * @param {{
 *   open: boolean,
 *   onClose: () => void,
 *   size?: 'sm'|'md'|'lg'|'xl',
 *   title?: string,
 *   subtitle?: string,
 *   className?: string,
 * }} props
 */
export function Modal({ open, onClose, size = 'md', title, subtitle, children, className = '' }) {
  const dialogRef = useRef(null);

  useEffect(() => {
    if (!open) return;
    const onKey = (e) => { if (e.key === 'Escape') onClose(); };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  useEffect(() => {
    if (open) {
      document.body.style.overflow = 'hidden';
      dialogRef.current?.focus();
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [open]);

  if (!open) return null;

  const cls = [
    'ds-modal',
    size !== 'md' ? 'ds-modal--' + size : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <div
      className="ds-modal-overlay"
      onClick={(e) => e.target === e.currentTarget && onClose()}
      aria-modal="true"
      role="dialog"
      aria-labelledby={title ? 'modal-title' : undefined}
    >
      <div ref={dialogRef} className={cls} tabIndex={-1}>
        {(title || subtitle) && (
          <div className="ds-modal-header">
            <div>
              {title    && <div className="ds-modal-title"    id="modal-title">{title}</div>}
              {subtitle && <div className="ds-modal-subtitle">{subtitle}</div>}
            </div>
            <button className="ds-modal-close" onClick={onClose} aria-label="Close modal">
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                <path d="M18 6 6 18"/><path d="m6 6 12 12"/>
              </svg>
            </button>
          </div>
        )}
        {children}
      </div>
    </div>
  );
}

export function ModalBody({ children, className = '' }) {
  return <div className={'ds-modal-body ' + className}>{children}</div>;
}

export function ModalFooter({ children, className = '' }) {
  return <div className={'ds-modal-footer ' + className}>{children}</div>;
}
`;
}

function genAvatarJsx() {
  return `/**
 * @param {{
 *   src?: string,
 *   alt?: string,
 *   name?: string,
 *   size?: 'xs'|'sm'|'md'|'lg'|'xl'|'2xl',
 *   shape?: 'circle'|'square',
 *   status?: 'online'|'away'|'busy'|'offline',
 *   className?: string,
 * }} props
 */
export function Avatar({ src, alt, name, size = 'md', shape = 'circle', status, className = '' }) {
  const initials = name
    ? name.split(' ').slice(0, 2).map(w => w[0]).join('').toUpperCase()
    : '?';

  const cls = [
    'ds-avatar',
    size !== 'md' ? 'ds-avatar--' + size : '',
    shape === 'square' ? 'ds-avatar--square' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <span className={cls} aria-label={alt || name || 'Avatar'}>
      {src
        ? <img src={src} alt={alt || name || ''} className="ds-avatar-img" />
        : <span className="ds-avatar-initials" aria-hidden="true">{initials}</span>
      }
      {status && (
        <span className={'ds-avatar-status ds-avatar-status--' + status} aria-label={status} />
      )}
    </span>
  );
}

/**
 * Avatar group — overlapping stack
 */
export function AvatarGroup({ avatars = [], max = 4, className = '' }) {
  const visible = avatars.slice(0, max);
  const overflow = avatars.length - max;
  return (
    <div className={'ds-avatar-group ' + className}>
      {visible.map((props, i) => <Avatar key={i} {...props} />)}
      {overflow > 0 && (
        <span className="ds-avatar" aria-label={'and ' + overflow + ' more'}>
          +{overflow}
        </span>
      )}
    </div>
  );
}
`;
}

function genTableJsx() {
  return `import { useState } from 'react';

/**
 * @param {{
 *   columns: Array<{ key: string, label: string, sortable?: boolean, width?: string }>,
 *   data: Array<Record<string, any>>,
 *   keyField?: string,
 *   striped?: boolean,
 *   bordered?: boolean,
 *   compact?: boolean,
 *   hoverable?: boolean,
 *   renderCell?: (key: string, value: any, row: any) => React.ReactNode,
 *   className?: string,
 * }} props
 */
export function Table({
  columns = [],
  data = [],
  keyField = 'id',
  striped = false,
  bordered = false,
  compact = false,
  hoverable = true,
  renderCell,
  className = '',
}) {
  const [sortKey,  setSortKey]  = useState(null);
  const [sortDir,  setSortDir]  = useState('asc');

  function handleSort(key) {
    if (sortKey === key) {
      setSortDir(d => d === 'asc' ? 'desc' : 'asc');
    } else {
      setSortKey(key);
      setSortDir('asc');
    }
  }

  const sorted = sortKey
    ? [...data].sort((a, b) => {
        const va = a[sortKey], vb = b[sortKey];
        const order = va < vb ? -1 : va > vb ? 1 : 0;
        return sortDir === 'asc' ? order : -order;
      })
    : data;

  const tableCls = [
    'ds-table',
    striped   ? 'ds-table--striped'   : '',
    bordered  ? 'ds-table--bordered'  : '',
    compact   ? 'ds-table--compact'   : '',
    hoverable ? 'ds-table--hoverable' : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <div className="ds-table-wrap">
      <table className={tableCls}>
        <thead>
          <tr>
            {columns.map(col => (
              <th
                key={col.key}
                className={col.sortable ? 'ds-th-sortable' + (sortKey === col.key ? ' is-sorted' : '') : ''}
                style={col.width ? { width: col.width } : undefined}
                onClick={col.sortable ? () => handleSort(col.key) : undefined}
                aria-sort={sortKey === col.key ? (sortDir === 'asc' ? 'ascending' : 'descending') : undefined}
              >
                {col.label}
                {col.sortable && (
                  <span className="ds-sort-icon" aria-hidden="true">
                    {sortKey === col.key ? (sortDir === 'asc' ? ' ↑' : ' ↓') : ' ↕'}
                  </span>
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sorted.length === 0 ? (
            <tr>
              <td colSpan={columns.length} style={{ textAlign: 'center', padding: '32px', color: 'var(--ds-neutral-600)' }}>
                No data
              </td>
            </tr>
          ) : sorted.map((row, i) => (
            <tr key={row[keyField] ?? i}>
              {columns.map(col => (
                <td key={col.key}>
                  {renderCell ? renderCell(col.key, row[col.key], row) : String(row[col.key] ?? '')}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
`;
}

function genSpinnerJsx() {
  return `/**
 * @param {{
 *   size?: 'xs'|'sm'|'md'|'lg'|'xl',
 *   muted?: boolean,
 *   className?: string,
 * }} props
 */
export function Spinner({ size = 'md', muted = false, className = '', ...rest }) {
  const cls = [
    'ds-spinner',
    size !== 'md' ? 'ds-spinner--' + size : '',
    muted ? 'ds-spinner--muted' : '',
    className,
  ].filter(Boolean).join(' ');
  return <span className={cls} role="status" aria-label="Loading" {...rest} />;
}

/**
 * @param {{
 *   value: number,
 *   max?: number,
 *   size?: 'sm'|'md'|'lg',
 *   variant?: 'default'|'success'|'warning'|'danger',
 *   className?: string,
 * }} props
 */
export function Progress({ value = 0, max = 100, size = 'md', variant = 'default', className = '' }) {
  const pct = Math.min(100, Math.max(0, (value / max) * 100));
  return (
    <div
      className={'ds-progress' + (size !== 'md' ? ' ds-progress--' + size : '') + (className ? ' ' + className : '')}
      role="progressbar"
      aria-valuenow={value}
      aria-valuemin={0}
      aria-valuemax={max}
    >
      <div
        className={'ds-progress-bar' + (variant !== 'default' ? ' ds-progress-bar--' + variant : '')}
        style={{ width: pct + '%' }}
      />
    </div>
  );
}

/**
 * Skeleton loading placeholder
 * @param {{ width?: string|number, height?: string|number, variant?: 'text'|'title'|'avatar'|'circle', className?: string }} props
 */
export function Skeleton({ width, height, variant = 'text', className = '', style, ...rest }) {
  return (
    <div
      className={'ds-skeleton ds-skeleton--' + variant + (className ? ' ' + className : '')}
      style={{ width, height, ...style }}
      aria-hidden="true"
      {...rest}
    />
  );
}

/**
 * Empty state with icon, title, description, and optional action
 */
export function EmptyState({ icon, title, description, action, className = '' }) {
  return (
    <div className={'ds-empty ' + className} role="status">
      {icon && <div className="ds-empty-icon">{icon}</div>}
      {title       && <div className="ds-empty-title">{title}</div>}
      {description && <div className="ds-empty-desc">{description}</div>}
      {action}
    </div>
  );
}
`;
}

function genReactIndexJs(name) {
  return `// ${name} — React component library
// Import once: import './tokens.css'; import './components.css';
// Then import components from here.

export { Button, ButtonGroup }       from './Button.jsx';
export { Field, Input, Textarea, Select, SearchInput, Checkbox, Radio, Toggle } from './Input.jsx';
export { Badge }                     from './Badge.jsx';
export { Alert, Callout }            from './Alert.jsx';
export { Card, CardHeader, CardTitle, CardSubtitle, CardBody, CardFooter, StatCard } from './Card.jsx';
export { Tabs, TabList, Tab, TabPanel } from './Tabs.jsx';
export { Modal, ModalBody, ModalFooter } from './Modal.jsx';
export { Avatar, AvatarGroup }       from './Avatar.jsx';
export { Table }                     from './Table.jsx';
export { Spinner, Progress, Skeleton, EmptyState } from './Spinner.jsx';
`;
}

// ── HTML examples file ────────────────────────────────────────────────

function genExamplesHtml(name) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${name} — Component Examples</title>
<link rel="stylesheet" href="../tokens.css">
<link rel="stylesheet" href="../components.css">
<style>
  body {
    background: var(--ds-surface);
    color: var(--ds-neutral-900);
    font-family: var(--ds-font-body);
    padding: 40px;
    margin: 0;
    line-height: 1.5;
  }
  .section { margin-bottom: 48px; }
  .section-title {
    font-family: var(--ds-font-display);
    font-size: var(--ds-text-lg);
    font-weight: var(--ds-weight-semibold);
    color: var(--ds-neutral-900);
    margin: 0 0 16px;
    padding-bottom: 10px;
    border-bottom: 1px solid var(--ds-neutral-200);
  }
  .example-row { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; margin-bottom: 12px; }
</style>
</head>
<body>

<h1 style="font-family:var(--ds-font-display);font-size:var(--ds-text-2xl);margin:0 0 8px;">${name}</h1>
<p style="color:var(--ds-neutral-600);margin:0 0 40px;">Component library — generated by Design System Studio</p>

<!-- Buttons -->
<div class="section">
  <div class="section-title">Buttons</div>
  <div class="example-row">
    <button class="ds-btn ds-btn--primary">Primary</button>
    <button class="ds-btn ds-btn--secondary">Secondary</button>
    <button class="ds-btn ds-btn--tertiary">Tertiary</button>
    <button class="ds-btn ds-btn--ghost">Ghost</button>
    <button class="ds-btn ds-btn--danger">Danger</button>
    <button class="ds-btn ds-btn--success">Success</button>
    <button class="ds-btn ds-btn--link">Link</button>
  </div>
  <div class="example-row">
    <button class="ds-btn ds-btn--primary ds-btn--xs">XSmall</button>
    <button class="ds-btn ds-btn--primary ds-btn--sm">Small</button>
    <button class="ds-btn ds-btn--primary">Medium</button>
    <button class="ds-btn ds-btn--primary ds-btn--lg">Large</button>
    <button class="ds-btn ds-btn--primary ds-btn--xl">XLarge</button>
  </div>
  <div class="example-row">
    <button class="ds-btn ds-btn--primary" disabled>Disabled</button>
    <button class="ds-btn ds-btn--ghost ds-btn--icon" title="Search">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
        <circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>
      </svg>
    </button>
  </div>
</div>

<!-- Badges -->
<div class="section">
  <div class="section-title">Badges</div>
  <div class="example-row">
    <span class="ds-badge ds-badge--primary">Primary</span>
    <span class="ds-badge ds-badge--success">Success</span>
    <span class="ds-badge ds-badge--warning">Warning</span>
    <span class="ds-badge ds-badge--danger">Danger</span>
    <span class="ds-badge ds-badge--info">Info</span>
    <span class="ds-badge ds-badge--neutral">Neutral</span>
  </div>
  <div class="example-row">
    <span class="ds-badge ds-badge--success ds-badge--subtle">Subtle</span>
    <span class="ds-badge ds-badge--warning ds-badge--subtle">Subtle</span>
    <span class="ds-badge ds-badge--danger ds-badge--subtle">Subtle</span>
    <span class="ds-badge ds-badge--success ds-badge--outline">Outline</span>
    <span class="ds-badge ds-badge--primary ds-badge--pill">Pill</span>
    <span class="ds-badge ds-badge--success ds-badge--subtle">
      <span class="ds-badge-dot"></span> Active
    </span>
  </div>
</div>

<!-- Alerts -->
<div class="section">
  <div class="section-title">Alerts</div>
  <div class="ds-stack--sm">
    <div class="ds-alert ds-alert--success">
      <span class="ds-alert-icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><path d="m9 11 3 3L22 4"/></svg>
      </span>
      <div class="ds-alert-body">
        <div class="ds-alert-title">Changes saved</div>
        <div class="ds-alert-desc">Your profile has been updated successfully.</div>
      </div>
    </div>
    <div class="ds-alert ds-alert--warning">
      <span class="ds-alert-icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
      </span>
      <div class="ds-alert-body">
        <div class="ds-alert-title">Action required</div>
        <div class="ds-alert-desc">Please verify your email address to continue.</div>
      </div>
    </div>
    <div class="ds-alert ds-alert--danger">
      <span class="ds-alert-icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/></svg>
      </span>
      <div class="ds-alert-body">
        <div class="ds-alert-title">Payment failed</div>
        <div class="ds-alert-desc">We could not process your card. Please try again.</div>
      </div>
    </div>
    <div class="ds-alert ds-alert--info">
      <span class="ds-alert-icon">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>
      </span>
      <div class="ds-alert-body">
        <div class="ds-alert-title">New version available</div>
        <div class="ds-alert-desc">Refresh the page to get the latest features.</div>
      </div>
    </div>
  </div>
</div>

<!-- Form inputs -->
<div class="section">
  <div class="section-title">Form Inputs</div>
  <div style="max-width:480px" class="ds-stack">
    <div class="ds-field">
      <label class="ds-field-label is-required" for="name">Full name</label>
      <input class="ds-input" id="name" type="text" placeholder="Jane Smith" />
    </div>
    <div class="ds-field">
      <label class="ds-field-label" for="about">About</label>
      <textarea class="ds-textarea" id="about" placeholder="Tell us about yourself…"></textarea>
      <span class="ds-field-hint">Max 160 characters.</span>
    </div>
    <div class="ds-field">
      <label class="ds-field-label" for="role">Role</label>
      <select class="ds-select" id="role">
        <option>Designer</option>
        <option>Developer</option>
        <option>Product manager</option>
      </select>
    </div>
    <div class="ds-search">
      <span class="ds-search-icon">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
          <circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>
        </svg>
      </span>
      <input class="ds-input" type="search" placeholder="Search…" />
    </div>
    <div class="ds-field">
      <label class="ds-field-label" for="email-err">Email</label>
      <input class="ds-input is-error" id="email-err" type="email" value="not-an-email" />
      <span class="ds-field-error">Please enter a valid email address.</span>
    </div>
    <div class="ds-row" style="gap:20px;flex-wrap:wrap;">
      <label class="ds-checkbox-wrap">
        <input type="checkbox" class="ds-checkbox" checked /> <span class="ds-checkbox-label">Checked</span>
      </label>
      <label class="ds-checkbox-wrap">
        <input type="checkbox" class="ds-checkbox" /> <span class="ds-checkbox-label">Unchecked</span>
      </label>
      <label class="ds-radio-wrap">
        <input type="radio" class="ds-radio" name="r1" checked /> <span class="ds-radio-label">Option A</span>
      </label>
      <label class="ds-radio-wrap">
        <input type="radio" class="ds-radio" name="r1" /> <span class="ds-radio-label">Option B</span>
      </label>
    </div>
    <div class="ds-toggle-wrap">
      <span class="ds-toggle">
        <input type="checkbox" checked id="t1" />
        <span class="ds-toggle-track"></span>
        <span class="ds-toggle-thumb"></span>
      </span>
      <label class="ds-toggle-label" for="t1">Email notifications</label>
    </div>
  </div>
</div>

<!-- Cards -->
<div class="section">
  <div class="section-title">Cards</div>
  <div class="ds-grid ds-grid--3" style="max-width:900px;">
    <div class="ds-card">
      <div class="ds-card-header">
        <div>
          <div class="ds-card-title">Default card</div>
          <div class="ds-card-subtitle">With header and body</div>
        </div>
      </div>
      <div class="ds-card-body">Body content goes here.</div>
    </div>
    <a href="#" class="ds-card ds-card--interactive">
      <div class="ds-card-body">
        <div class="ds-card-title">Interactive card</div>
        <div class="ds-card-subtitle" style="margin-top:4px;">Hover to see lift effect.</div>
      </div>
    </a>
    <div class="ds-card ds-stat">
      <div class="ds-stat-label">Monthly Revenue</div>
      <div class="ds-stat-value">$48,295</div>
      <div class="ds-stat-change ds-stat-change--up">▲ 12.4% vs last month</div>
    </div>
  </div>
</div>

<!-- Tabs -->
<div class="section">
  <div class="section-title">Tabs</div>
  <div class="ds-stack--lg">
    <!-- Line tabs -->
    <div>
      <div class="ds-tab-list" role="tablist">
        <button class="ds-tab is-active" role="tab">Overview</button>
        <button class="ds-tab" role="tab">Activity</button>
        <button class="ds-tab" role="tab">Settings</button>
      </div>
      <div class="ds-tab-panel">Tab content panel.</div>
    </div>
    <!-- Pill tabs -->
    <div class="ds-tabs--pill">
      <div class="ds-tab-list" role="tablist">
        <button class="ds-tab is-active" role="tab">All</button>
        <button class="ds-tab" role="tab">Active</button>
        <button class="ds-tab" role="tab">Draft</button>
        <button class="ds-tab" role="tab">Archived</button>
      </div>
      <div class="ds-tab-panel">Pill tab content.</div>
    </div>
    <!-- Boxed tabs -->
    <div class="ds-tabs--boxed">
      <div class="ds-tab-list" role="tablist">
        <button class="ds-tab is-active" role="tab">Preview</button>
        <button class="ds-tab" role="tab">Code</button>
      </div>
      <div class="ds-tab-panel">Boxed tab content.</div>
    </div>
  </div>
</div>

<!-- Avatars -->
<div class="section">
  <div class="section-title">Avatars</div>
  <div class="example-row" style="align-items:flex-end;">
    <span class="ds-avatar ds-avatar--xs">AB</span>
    <span class="ds-avatar ds-avatar--sm">CD</span>
    <span class="ds-avatar">EF</span>
    <span class="ds-avatar ds-avatar--lg">GH</span>
    <span class="ds-avatar ds-avatar--xl">
      IJ
      <span class="ds-avatar-status ds-avatar-status--online"></span>
    </span>
  </div>
  <div class="example-row" style="margin-top:16px;">
    <div class="ds-avatar-group">
      <span class="ds-avatar ds-avatar--sm">A1</span>
      <span class="ds-avatar ds-avatar--sm">B2</span>
      <span class="ds-avatar ds-avatar--sm">C3</span>
      <span class="ds-avatar ds-avatar--sm">+4</span>
    </div>
  </div>
</div>

<!-- Progress & Spinner -->
<div class="section">
  <div class="section-title">Progress & Spinner</div>
  <div class="ds-stack" style="max-width:400px;">
    <div class="ds-progress"><div class="ds-progress-bar" style="width:65%"></div></div>
    <div class="ds-progress"><div class="ds-progress-bar ds-progress-bar--success" style="width:80%"></div></div>
    <div class="ds-progress"><div class="ds-progress-bar ds-progress-bar--warning" style="width:40%"></div></div>
    <div class="ds-progress"><div class="ds-progress-bar ds-progress-bar--danger" style="width:20%"></div></div>
  </div>
  <div class="example-row" style="margin-top:20px;">
    <span class="ds-spinner ds-spinner--xs"></span>
    <span class="ds-spinner ds-spinner--sm"></span>
    <span class="ds-spinner"></span>
    <span class="ds-spinner ds-spinner--lg"></span>
    <span class="ds-spinner ds-spinner--xl"></span>
  </div>
</div>

<!-- Table -->
<div class="section">
  <div class="section-title">Table</div>
  <div class="ds-table-wrap" style="max-width:700px;">
    <table class="ds-table ds-table--striped ds-table--hoverable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Role</th>
          <th>Status</th>
          <th>Joined</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Jane Smith</td>
          <td>Designer</td>
          <td><span class="ds-badge ds-badge--success ds-badge--subtle"><span class="ds-badge-dot"></span> Active</span></td>
          <td>Jan 2023</td>
        </tr>
        <tr>
          <td>Tom Walker</td>
          <td>Developer</td>
          <td><span class="ds-badge ds-badge--warning ds-badge--subtle">Away</span></td>
          <td>Mar 2023</td>
        </tr>
        <tr>
          <td>Sarah Chen</td>
          <td>PM</td>
          <td><span class="ds-badge ds-badge--neutral">Inactive</span></td>
          <td>Jun 2022</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<!-- Skeleton -->
<div class="section">
  <div class="section-title">Skeleton</div>
  <div class="ds-card" style="max-width:360px;">
    <div class="ds-card-body ds-stack--sm">
      <div class="ds-row">
        <div class="ds-skeleton ds-skeleton--avatar" style="width:40px;height:40px;flex-shrink:0;"></div>
        <div style="flex:1;display:flex;flex-direction:column;gap:6px;">
          <div class="ds-skeleton ds-skeleton--title" style="width:60%;"></div>
          <div class="ds-skeleton ds-skeleton--text" style="width:80%;"></div>
        </div>
      </div>
      <div class="ds-skeleton ds-skeleton--text"></div>
      <div class="ds-skeleton ds-skeleton--text" style="width:70%;"></div>
    </div>
  </div>
</div>

</body>
</html>
`;
}

// ── CLAUDE.md generator ───────────────────────────────────────────────

function genClaudeMd(tokens, cssVars, name) {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  const colorSection = [
    '--ds-brand',        '--ds-brand-hover',   '--ds-brand-dark',   '--ds-brand-light',
    '--ds-secondary',    '--ds-secondary-hover',
    '--ds-tertiary',     '--ds-tertiary-hover',
    '--ds-success',      '--ds-success-hover',  '--ds-success-subtle', '--ds-success-on-subtle',
    '--ds-warning',      '--ds-warning-hover',  '--ds-warning-subtle', '--ds-warning-on-subtle',
    '--ds-danger',       '--ds-danger-hover',   '--ds-danger-subtle',  '--ds-danger-on-subtle',
    '--ds-info',         '--ds-info-hover',     '--ds-info-subtle',    '--ds-info-on-subtle',
    '--ds-surface',      '--ds-surface-1',      '--ds-surface-2',
    '--ds-neutral-100',  '--ds-neutral-200',    '--ds-neutral-300',    '--ds-neutral-400',
    '--ds-neutral-600',  '--ds-neutral-800',    '--ds-neutral-900',
  ].map(k => cssVars[k] ? `  ${k}: ${cssVars[k]};` : null).filter(Boolean).join('\n');

  const spaceSection = Object.entries(cssVars)
    .filter(([k]) => k.startsWith('--ds-space'))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  const textSection = Object.entries(cssVars)
    .filter(([k]) => k.startsWith('--ds-text'))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  const radiusSection = Object.entries(cssVars)
    .filter(([k]) => k.startsWith('--ds-radius'))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  const shadowSection = Object.entries(cssVars)
    .filter(([k]) => k.startsWith('--ds-shadow'))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  const motionSection = Object.entries(cssVars)
    .filter(([k]) => k.startsWith('--ds-duration') || k.startsWith('--ds-ease') || k.startsWith('--ds-transition'))
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n');

  return `---
name: ${slug}
description: Apply the ${name} design system across all frontend projects. Use this skill whenever building React components, HTML/CSS UI, landing pages, dashboards, forms, data tables, modals, navigation, or any visual interface. Trigger when asked to: build UI, create components, style pages, match brand, use design tokens, implement dark mode, or create accessible interfaces.
---

# ${name} — Design System Reference

Generated by Design System Studio. This file is the single source of truth for building UI in this design system.

**Brand:** \`${tokens.brand}\` · **Font:** ${tokens.fontDisplay} / ${tokens.fontBody} · **Radius:** ${tokens.radiusMd} · **Borders:** ${tokens.borderStyle}

---

## Setup

\`\`\`html
<!-- HTML/CSS projects -->
<link rel="stylesheet" href="tokens.css" />
<link rel="stylesheet" href="components.css" />
\`\`\`

\`\`\`js
// React projects (once at app root)
import './tokens.css';
import './components.css';
import { Button, Card, Badge, ... } from './react/index.js';
\`\`\`

---

## Design Tokens — Full Reference

### Colors
\`\`\`css
:root {
${colorSection}
}
\`\`\`

### Typography
\`\`\`css
:root {
  --ds-font-display: ${cssVars['--ds-font-display']};
  --ds-font-body:    ${cssVars['--ds-font-body']};
  --ds-font-mono:    ${cssVars['--ds-font-mono']};
${textSection}
}
\`\`\`

### Spacing
\`\`\`css
:root {
${spaceSection}
}
\`\`\`

### Shape
\`\`\`css
:root {
${radiusSection}
  --ds-border-style: ${cssVars['--ds-border-style']};
${shadowSection}
}
\`\`\`

### Motion
\`\`\`css
:root {
${motionSection}
}
\`\`\`

---

## Core Principles

1. **Tokens over values** — never hardcode hex or px; use \`var(--ds-brand)\`, \`var(--ds-space-md)\`
2. **Semantic naming** — \`--ds-danger\` not \`--ds-red\`; \`--ds-neutral-600\` for muted text
3. **Dark mode is automatic** — the token values switch, components follow; never write \`@media (prefers-color-scheme)\` overrides
4. **Scale discipline** — only spacing values from the scale; no arbitrary pixel gaps
5. **Accessibility** — every interactive element needs focus-visible state, ARIA roles, and ≥4.5:1 text contrast

---

## Component Class Reference

### Buttons
\`\`\`html
<!-- Variants -->
<button class="ds-btn ds-btn--primary">Primary</button>
<button class="ds-btn ds-btn--secondary">Secondary</button>
<button class="ds-btn ds-btn--tertiary">Tertiary</button>
<button class="ds-btn ds-btn--ghost">Ghost</button>
<button class="ds-btn ds-btn--danger">Danger</button>
<button class="ds-btn ds-btn--success">Success</button>
<button class="ds-btn ds-btn--link">Link</button>
<button class="ds-btn ds-btn--primary-subtle">Subtle Primary</button>

<!-- Sizes: xs · sm · (md default) · lg · xl -->
<button class="ds-btn ds-btn--primary ds-btn--sm">Small</button>
<button class="ds-btn ds-btn--primary ds-btn--lg">Large</button>

<!-- States -->
<button class="ds-btn ds-btn--primary" disabled>Disabled</button>
<button class="ds-btn ds-btn--primary ds-btn--wide">Full width</button>
<button class="ds-btn ds-btn--ghost ds-btn--icon">⊕</button>
\`\`\`

### React: Button
\`\`\`jsx
<Button variant="primary" size="lg" onClick={save}>Save changes</Button>
<Button variant="ghost" leftIcon={<Icon />}>With icon</Button>
<Button variant="danger" loading>Deleting…</Button>
<Button variant="link" href="/docs">Read docs</Button>
\`\`\`
Props: \`variant\` · \`size\` · \`loading\` · \`leftIcon\` · \`rightIcon\` · \`wide\` · \`disabled\`

---

### Form Inputs
\`\`\`html
<!-- Field wrapper with label + hint + error -->
<div class="ds-field">
  <label class="ds-field-label is-required" for="x">Label</label>
  <input class="ds-input" id="x" placeholder="Placeholder" />
  <span class="ds-field-hint">Helper text.</span>
</div>

<!-- Error state -->
<input class="ds-input is-error" />
<span class="ds-field-error">Required field.</span>

<!-- Sizes: --sm · (md default) · --lg -->
<input class="ds-input ds-input--sm" />

<!-- Textarea -->
<textarea class="ds-textarea" rows="4"></textarea>

<!-- Select -->
<select class="ds-select"><option>Choice</option></select>

<!-- Search -->
<div class="ds-search">
  <span class="ds-search-icon">🔍</span>
  <input class="ds-input" type="search" placeholder="Search…" />
</div>

<!-- Checkbox / Radio -->
<label class="ds-checkbox-wrap">
  <input type="checkbox" class="ds-checkbox" />
  <span class="ds-checkbox-label">Option</span>
</label>

<!-- Toggle -->
<label class="ds-toggle-wrap">
  <span class="ds-toggle">
    <input type="checkbox" />
    <span class="ds-toggle-track"></span>
    <span class="ds-toggle-thumb"></span>
  </span>
  <span class="ds-toggle-label">Enable feature</span>
</label>
\`\`\`

### React: Form
\`\`\`jsx
<Field label="Email" hint="We won't share this." required htmlFor="email">
  <Input id="email" type="email" placeholder="you@co.com" />
</Field>
<Field label="Notes" htmlFor="notes">
  <Textarea id="notes" rows={4} />
</Field>
<Checkbox label="I agree to the terms" />
<Toggle label="Email notifications" defaultChecked />
<SearchInput placeholder="Search users…" />
\`\`\`

---

### Badge
\`\`\`html
<!-- Variants: primary · success · warning · danger · info · neutral -->
<span class="ds-badge ds-badge--success">Active</span>
<span class="ds-badge ds-badge--warning ds-badge--subtle">Pending</span>
<span class="ds-badge ds-badge--danger ds-badge--outline">Error</span>
<span class="ds-badge ds-badge--primary ds-badge--pill">New</span>
<!-- With dot -->
<span class="ds-badge ds-badge--success ds-badge--subtle">
  <span class="ds-badge-dot"></span> Online
</span>
\`\`\`

### React: Badge
\`\`\`jsx
<Badge variant="success">Active</Badge>
<Badge variant="warning" style="subtle">Pending</Badge>
<Badge variant="danger" style="outline">Error</Badge>
<Badge variant="primary" pill dot>New</Badge>
\`\`\`
Props: \`variant\` · \`style\` (filled/subtle/outline) · \`size\` · \`pill\` · \`dot\`

---

### Alert
\`\`\`html
<div class="ds-alert ds-alert--success">
  <span class="ds-alert-icon">✓</span>
  <div class="ds-alert-body">
    <div class="ds-alert-title">Saved!</div>
    <div class="ds-alert-desc">Your changes have been saved.</div>
  </div>
</div>
<!-- Variants: success · warning · danger · info -->

<!-- Callout (left border) -->
<div class="ds-callout ds-callout--info">
  <div class="ds-callout-title">Note</div>
  <div class="ds-callout-body">This is a callout message.</div>
</div>
\`\`\`

### React: Alert
\`\`\`jsx
<Alert variant="success" title="Saved!" dismissible>Changes saved.</Alert>
<Alert variant="danger"  title="Error"  icon={false}>Something went wrong.</Alert>
<Callout variant="info" title="Heads up">This is informational.</Callout>
\`\`\`

---

### Card
\`\`\`html
<!-- Base card -->
<div class="ds-card">
  <div class="ds-card-header">
    <div class="ds-card-title">Title</div>
  </div>
  <div class="ds-card-body">Content</div>
  <div class="ds-card-footer">
    <button class="ds-btn ds-btn--primary ds-btn--sm">Action</button>
  </div>
</div>

<!-- Variants: (default) · bordered · ghost · elevated -->
<div class="ds-card ds-card--ghost">...</div>

<!-- Interactive (clickable) -->
<a href="#" class="ds-card ds-card--interactive">...</a>

<!-- Stat card -->
<div class="ds-card ds-stat">
  <div class="ds-stat-label">MRR</div>
  <div class="ds-stat-value">$12,400</div>
  <div class="ds-stat-change ds-stat-change--up">▲ 8.2%</div>
</div>
\`\`\`

### React: Card
\`\`\`jsx
<Card>
  <CardHeader><CardTitle>Title</CardTitle><CardSubtitle>Subtitle</CardSubtitle></CardHeader>
  <CardBody>Content goes here.</CardBody>
  <CardFooter><Button size="sm">Action</Button></CardFooter>
</Card>

<Card variant="interactive" as="a" href="/detail">Clickable card</Card>
<StatCard label="Revenue" value="$48k" change="+12%" changeDir="up" />
\`\`\`

---

### Tabs (3 variants)
\`\`\`html
<!-- Line (default) -->
<div class="ds-tab-list" role="tablist">
  <button class="ds-tab is-active" role="tab">Tab 1</button>
  <button class="ds-tab" role="tab">Tab 2</button>
</div>
<div class="ds-tab-panel">Content</div>

<!-- Pill tabs: wrap with ds-tabs--pill -->
<div class="ds-tabs--pill">
  <div class="ds-tab-list">...</div>
</div>

<!-- Boxed tabs: wrap with ds-tabs--boxed -->
<div class="ds-tabs--boxed">
  <div class="ds-tab-list">...</div>
  <div class="ds-tab-panel">...</div> <!-- panel gets border here -->
</div>
\`\`\`

### React: Tabs
\`\`\`jsx
<Tabs defaultValue="overview" variant="pill">
  <TabList>
    <Tab value="overview">Overview</Tab>
    <Tab value="activity" count={12}>Activity</Tab>
    <Tab value="settings" disabled>Settings</Tab>
  </TabList>
  <TabPanel value="overview">Overview content</TabPanel>
  <TabPanel value="activity">Activity content</TabPanel>
</Tabs>
\`\`\`
Tab variants: \`line\` (default) · \`pill\` · \`boxed\`

---

### Modal
\`\`\`html
<div class="ds-modal-overlay">
  <div class="ds-modal">
    <div class="ds-modal-header">
      <div class="ds-modal-title">Modal title</div>
      <button class="ds-modal-close">✕</button>
    </div>
    <div class="ds-modal-body">Modal content goes here.</div>
    <div class="ds-modal-footer">
      <button class="ds-btn ds-btn--ghost ds-btn--sm">Cancel</button>
      <button class="ds-btn ds-btn--primary ds-btn--sm">Confirm</button>
    </div>
  </div>
</div>
<!-- Sizes: ds-modal--sm · (md default) · ds-modal--lg · ds-modal--xl -->
\`\`\`

### React: Modal
\`\`\`jsx
const [open, setOpen] = useState(false);

<Modal open={open} onClose={() => setOpen(false)} title="Delete item" subtitle="This cannot be undone." size="sm">
  <ModalBody>Are you sure you want to delete this item?</ModalBody>
  <ModalFooter>
    <Button variant="ghost" size="sm" onClick={() => setOpen(false)}>Cancel</Button>
    <Button variant="danger" size="sm" onClick={handleDelete}>Delete</Button>
  </ModalFooter>
</Modal>
\`\`\`

---

### Avatar
\`\`\`html
<!-- Sizes: xs · sm · (md default) · lg · xl · 2xl -->
<span class="ds-avatar">AB</span>
<span class="ds-avatar ds-avatar--lg">
  <img src="photo.jpg" class="ds-avatar-img" />
  <span class="ds-avatar-status ds-avatar-status--online"></span>
</span>

<!-- Group -->
<div class="ds-avatar-group">
  <span class="ds-avatar ds-avatar--sm">A1</span>
  <span class="ds-avatar ds-avatar--sm">B2</span>
</div>
\`\`\`

### React: Avatar
\`\`\`jsx
<Avatar name="Jane Smith" size="lg" status="online" />
<Avatar src="/photo.jpg" alt="Jane" size="xl" />
<AvatarGroup avatars={[{name:'A'},{name:'B'},{name:'C'}]} max={3} />
\`\`\`

---

### Table
\`\`\`html
<div class="ds-table-wrap">
  <table class="ds-table ds-table--striped ds-table--hoverable">
    <thead><tr><th>Name</th><th>Status</th></tr></thead>
    <tbody>
      <tr><td>Item 1</td><td><span class="ds-badge ds-badge--success ds-badge--subtle">Active</span></td></tr>
    </tbody>
  </table>
</div>
<!-- Modifiers: striped · hoverable · bordered · compact -->
\`\`\`

### React: Table
\`\`\`jsx
<Table
  columns={[
    { key: 'name',   label: 'Name',   sortable: true },
    { key: 'status', label: 'Status', sortable: false },
  ]}
  data={rows}
  striped
  hoverable
  renderCell={(key, val, row) =>
    key === 'status' ? <Badge variant="success" style="subtle">{val}</Badge> : val
  }
/>
\`\`\`

---

### Spinner & Progress
\`\`\`html
<span class="ds-spinner"></span>
<span class="ds-spinner ds-spinner--lg"></span>
<span class="ds-spinner ds-spinner--muted"></span>

<div class="ds-progress">
  <div class="ds-progress-bar" style="width:65%"></div>
</div>
<div class="ds-progress">
  <div class="ds-progress-bar ds-progress-bar--success" style="width:90%"></div>
</div>
\`\`\`

### React: Spinner
\`\`\`jsx
<Spinner />
<Spinner size="lg" muted />
<Progress value={65} />
<Progress value={30} variant="danger" size="sm" />
<Skeleton variant="text" width="80%" />
<Skeleton variant="avatar" width={40} height={40} />
<EmptyState icon={<SearchIcon />} title="No results" description="Try a different search." action={<Button>Clear filters</Button>} />
\`\`\`

---

## Layout Utilities
\`\`\`html
<!-- Vertical stack -->
<div class="ds-stack">...</div>            <!-- gap: --ds-space-md -->
<div class="ds-stack ds-stack--sm">...</div>

<!-- Horizontal row -->
<div class="ds-row">...</div>              <!-- gap: --ds-space-sm, align center -->
<div class="ds-row ds-row--between">...</div>
<div class="ds-row ds-row--end">...</div>

<!-- Grid -->
<div class="ds-grid ds-grid--3">...</div>  <!-- 3 equal columns, responsive -->
<div class="ds-grid ds-grid--auto">...</div>

<!-- Divider -->
<hr class="ds-divider" />
\`\`\`

---

## Quality Checklist

- [ ] All colors use \`var(--ds-*)\` — no hardcoded hex
- [ ] All spacing uses \`--ds-space-*\` tokens
- [ ] Works in both light and dark mode (just change token values — no overrides)
- [ ] Interactive states: hover, focus-visible, disabled
- [ ] Text contrast ≥ 4.5:1 for body, ≥ 3:1 for large text
- [ ] Mobile: check at 375px viewport width
- [ ] Loading, empty, and error states handled
- [ ] ARIA roles and labels on all interactive and status elements
`;
}

// ── Main export orchestrator ──────────────────────────────────────────

export async function buildExportZip(tokens, cssVars, name) {
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const zip  = new JSZip();
  const root = zip.folder(slug);

  // Token files
  root.file('tokens.css',    genTokensCss(cssVars, name));
  root.file('tokens.js',     genTokensJs(cssVars, name));
  root.file('components.css', genComponentsCss(name));

  // React components
  const react = root.folder('react');
  react.file('Button.jsx',  genButtonJsx());
  react.file('Input.jsx',   genInputJsx());
  react.file('Badge.jsx',   genBadgeJsx());
  react.file('Alert.jsx',   genAlertJsx());
  react.file('Card.jsx',    genCardJsx());
  react.file('Tabs.jsx',    genTabsJsx());
  react.file('Modal.jsx',   genModalJsx());
  react.file('Avatar.jsx',  genAvatarJsx());
  react.file('Table.jsx',   genTableJsx());
  react.file('Spinner.jsx', genSpinnerJsx());
  react.file('index.js',    genReactIndexJs(name));

  // HTML/CSS reference
  const htmlcss = root.folder('html-css');
  htmlcss.file('examples.html', genExamplesHtml(name));

  // CLAUDE.md skill file
  root.file('CLAUDE.md', genClaudeMd(tokens, cssVars, name));

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
  saveAs(blob, `${slug}.zip`);
}
